#1 pull request
Bae-tory/Android_CodeReview pull request #1
Opened 2021-10-22 00:32 UTC by johits

#1 pull request 코드 리팩토링

2021-10-22 00:42 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/adapter/ImageAdapter.kt
>          val binding = RvImageBinding.inflate(LayoutInflater.from(parent.context), parent, false)
여긴 뷰바인딩 쓰신 이유가 있나요?

2021-10-22 00:42 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/adapter/ImageAdapter.kt
> +    override fun submitList(list: List<SearchData>?) {
이건 왜 따로 구현하신건가요?

2021-10-22 00:43 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +    val type = "blog"
상수는 프로퍼티로 쓰지 말아주세요

2021-10-22 00:44 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +            model = Model()
변수명이 너무 애매합니다.

2021-10-22 00:44 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Cafe.kt
> +    val type = "cafe"
위 코멘트와 동일

2021-10-22 00:44 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Cafe.kt
> +            model = Model()
위 코멘트와 동일

2021-10-22 00:44 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Image.kt
> +    val type = "image"
상동

2021-10-22 00:44 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Image.kt
> +            model = Model()
상동

2021-10-22 00:44 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/News.kt
> +    val type = "news"
상동

2021-10-22 00:44 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/News.kt
> +            model = Model()
상동

2021-10-22 00:45 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +            if (type == "image") {
string 비교할때는 상수로 빼주세요

2021-10-22 00:45 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +    fun lookUp(type: String, context: Context, rv: RecyclerView) {
모델의 메서드가 context를 param으로 받지 않게 해주세요.

2021-10-22 00:46 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +                        )
보기 안좋지 않나요? 훨씬 많이 줄일 수 있어보입니다.

2021-10-22 00:47 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +        if (keyword != "") {
코틀린 함수를 이용해 바꿔주세요.

2021-10-22 00:47 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +        val retrofit = Retrofit.Builder()
이러면 search 할때마다 매번 새로운 객체를 생성하는데 이럴 필요 있나요?

2021-10-22 00:47 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +        context: Context,
context를 주입받지 않게 해주세요.

2021-10-22 00:48 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +    private val imageAdapter = ImageAdapter()
모델은 어뎁터를 알면 안됩니다.

2021-10-22 00:48 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +                    editor.apply()
shared 관련 것들은 ktx를 이용해주세요.

2021-10-22 00:49 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +            callGetSearch.enqueue(object : Callback<ResultGetSearch> {
1. enqueue를 쓰는 이유가 뭔가요? 주의해야 할 점이 뭔가요?
2. object : ~~ 이런식으로 쓰시는 이유가 있나요?

2021-10-22 00:49 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/NaverAPI.kt
>      @Headers(
헤더를 굳이 동적으로 추가시킨 이유가 있나요?

2021-10-22 00:50 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/SearchData.kt
> +    val thumbnail:String? = "",
Remote DTO는 default값이 특별한 경우가 아니고선 필요하지 않습니다.

2021-10-22 00:50 UTC, Bae-tory commented on app/src/main/res/layout/activity_main.xml
>  <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
constratint로 바꿔주세요.

2021-10-22 00:51 UTC, Bae-tory commented on app/src/main/res/layout/activity_main.xml
> +            android:text="블로그" />
하드코딩 말고 리소스로 빼주세요.
tools: 제외

2021-10-22 00:51 UTC, Bae-tory commented on app/src/main/res/layout/frg_blog.xml
> +                android:onClick="@{() ->model.search(fragment.type, fragment.category, etBlog.getText().toString(), fragment.context,rvBlog)}"
검색을 순식간에 여러번 누르면 무한으로 여러번 요청이 갈텐데 이걸 방지해주세요.

2021-10-22 00:55 UTC, Bae-tory requested changes

2021-10-22 00:55 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +class Model {
MVC를 구현한다고 하셨는데 Model의 존재이유가 뭔가요?(힌트: 독립) 코드를 보면 더 공부가 필요해 보입니다.
model이 어떤식으로 존재해야되는지 공부하고 수정해주세요.

2021-10-31 14:22 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +    val type = "blog"
상수 const val로 변경 // 698dbd22c91804b2872c3cd8bc8dd2b16bcc40f1

2021-10-31 14:28 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +            model = Model()
naverModel로 변수명 변경 // b76722f0ecb3f57ecc6bf00d030d256926e7db62

2021-10-31 14:29 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +            model = Model()
데이터바인딩시 fragment나 activity는 변수명을 그대로 fragment, activiy를 사용하던데 model도 model이라고 사용하면 안 되는 이유가 있나요?

2021-10-31 14:29 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Cafe.kt
> +            model = Model()
naverModel로 변수명 변경 // b76722f

2021-10-31 14:29 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Image.kt
> +    val type = "image"
naverModel로 변수명 변경 // b76722f

2021-10-31 14:30 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Image.kt
> +            model = Model()
naverModel로 변수명 변경 // b76722f

2021-10-31 14:30 UTC, johits commented on app/src/main/java/com/example/naversearch/category/News.kt
> +            model = Model()
naverModel로 변수명 변경 // b76722f

2021-10-31 14:32 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Image.kt
> +    val type = "image"
상수 const val로 변경 // 698dbd2

2021-10-31 14:32 UTC, johits commented on app/src/main/java/com/example/naversearch/category/News.kt
> +    val type = "news"
상수 const val로 변경 // 698dbd2

2021-10-31 14:35 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +            if (type == "image") {
상수로 변경 // c3fc2fa4b9dacd7f12fb4d9a866cb576062ba700

2021-11-01 12:10 UTC, johits commented on app/src/main/res/layout/frg_blog.xml
> +                android:onClick="@{() ->model.search(fragment.type, fragment.category, etBlog.getText().toString(), fragment.context,rvBlog)}"
검색 버튼 중복 클릭 방지 // 8676fcf1d3c6e372283f8953a235b2bdce13023f

2021-11-01 13:31 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +                        )
gson이용해서 코드 간략화 // 7ee8713aaf7c9894f2cfc99b4c5213520312ac8c

2021-11-02 00:05 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +            model = Model()
mode 객체명을 말씀드리는거예요

2021-11-02 12:38 UTC, johits commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +            model = Model()
아하 제가 이해한 게 맞다면 한 액티비티 또는 프래그먼트에 대한 모델이 여러개 있을 수도 있어서 그런 건가요?

2021-11-05 15:54 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +    fun lookUp(type: String, context: Context, rv: RecyclerView) {
context를 param으로 받지 않게 수정 // 53ee28e7c663eaa7c6084ac85f3728ac00652841

2021-11-05 15:55 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +        context: Context,
context를 param으로 받지 않게 수정 // 53ee28e

2021-11-05 16:18 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +        val retrofit = Retrofit.Builder()
shared 객체 중복 생성 수정 // d044909d673a3b5c00d7142331b58e8d558fc6bb 9e9edd90cd83fc24c48f4c8ea20d2babf3a72038

2021-11-09 13:45 UTC, Bae-tory requested changes

2021-11-09 13:45 UTC, Bae-tory commented on app/src/main/java/com/example/naversearch/category/Blog.kt
> +            naverModel = NaverModel(requireActivity().application)
여기서 그냥 sharedpref 객체를 주입해주세요. 그럼 model은 context를 몰라도 됩니다.

2021-11-10 16:13 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +    private val imageAdapter = ImageAdapter()
모델에서 textadapter 제거 // 3d3a9fd061678b61fe8d05c48bc72d8b48631038

2021-11-10 16:15 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +    private val imageAdapter = ImageAdapter()
textAdapter 분리했으나 검색 버튼 클릭시 뷰에 새로운 데이터를 뿌려주지 않는 문제 있어서 해결해야합니다. (diffutilcallback에서 oldlist와 newlist가 다르다는 것을 인식하지 못하는 것 같습니다.) ImageAdapter는 아직 분리 안 했습니다.

2021-11-11 15:01 UTC, johits commented on app/src/main/java/com/example/naversearch/model/Model.kt
> +    private val imageAdapter = ImageAdapter()
submitList 데이터 리사이클러뷰에 업데이트 안 되었던 에러 해결
// ca26dd5336c562e7620d9ac69be4345c740bc2f3
NaverModel에 있었던 imageadapter 제거
잘못된 코드 수정 및 중복 코드 제거
// b1e0db539513063f6a5d71873d5e860945946577
// 5ab39d88320b37822eec37260c69df1835d75e38

imageAdapter 리사이클러뷰에 검색결과가 보여지지 않는 에러 발생하여 해결해야 함

2021-11-12 00:05 UTC, merged

2021-11-12 00:13 UTC, Bae-tory commented
@johits 고생하셨어요~